# The name of the pipeline
name: Continues Integration

# Controls when the workflow runs. Here the workflow wil run whenever someone
# pushes code up or pulls code down from the repository from the main branch. 
on: # The trigger for the workflow to begin testing
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows to manually run the workflow from the Actions tab
  workflow_dispatch: 

# jobs define what the workflow does. So here we define what test we'd like our
# code to run, as well as which actions we'd like to preform. These jobs or tasks
# can run either in parallell or in sequence
jobs:
  test: # This workflow is defined as test
    # Defines what image the tasks will run on
    runs-on: ubuntu-latest
    # Stepss represent a sequence which the tasks will be preformed in.
    steps:
        # This test checks out the github repo under $GITHUB_WORKSPACE, so our jobs can access it
      - name: Check out Git-Hub repository
        uses: actions/checkout@v3
        # tests if able to run linux commands in our ubuntu image
      - name: Run a single line script to see if yaml works as intended
        run: |
          echo Hello, world!  
          echo The world responds hello back!
  
  build: # This workflow will define building and pushing a docker container
    runs-on: ubuntu-latest
    steps: 
        # Checks if possible to log into docker hub using Git-Hub secrets
      - name: Log into docker hub from Git-Hub actions
        uses: docker/login-action@v2
        with: # Defined in Git-Hub Secrets, the credentials for loggin into my Docker hub account
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      # Checks if possible to build the container as well pushing it to my Docker hub repository,
      - name: Build and push the docker container
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile # This file will build a folder and a text file at the root of the container
          push: true
          tags: ${{ secrets.DOCKER_USER }}/cicd_pipeline
        run: docker context
